# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M.Mazil
email: mohamed.mazil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Mohammed Mazil and im a young developer and here u can read about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simomazil.github.io" # the base hostname & protocol for your site
twitter_username: SimoMazil
github_username:  SimoMazil

# Build settings
markdown: kramdown
